Listen 81

ExtendedStatus On

<VirtualHost *:81>
    DocumentRoot /var/www/empty

    <Directory /var/www/empty>
        Options None
        AllowOverride None
        Require all denied
    </Directory>

    <Location "/server-status">
        SetHandler server-status
        Require all granted
    </Location>
</VirtualHost>
